**Задание 1**
Создайте numpy array с элементами от числа N до 0
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
import numpy as np
np.arange(10, -1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
x = np.arange(10, -1, -1)
print (np.diag(x))
print (np.trace(np.diag(x)))

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
55


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [33]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
print ( np.linalg.solve(a,b) )

[ 0.46666667  3.84444444 -5.55555556]


In [34]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Задание 4**
Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [15]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

In [16]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [27]:
cosine_list = []

for user in users_stats:
    aLength = np.linalg.norm( user )
    bLength = np.linalg.norm( next_user_stats )
    cosine = np.dot( user, next_user_stats ) / ( aLength * bLength )
    cosine_list.append(cosine)
    
print ( 'User alike:', cosine_list.index(max(cosine_list)) )
print ( 'Cosine:', max(cosine_list) )

User alike: 7
Cosine: 0.9486832980505138
